name: medicare
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  blur: ^3.1.0
  fluttertoast: ^8.0.9
  image_picker: ^0.8.5
  cupertino_icons: ^1.0.2
  dropdown_search: ^3.0.1
  flutter_spinkit: ^5.1.0
  flutter_animator: ^3.2.1
  cloudinary_sdk: ^4.0.0+8
  connectivity_plus: ^2.3.0
  multi_image_picker: ^4.8.0
  shared_preferences: ^2.0.13
  font_awesome_flutter: ^10.1.0
  material_floating_search_bar: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
